### ISSUE TITLE
Linked work item fields selected to display are disappearing

### ISSUE THREAD

**Issue by jenkrall** [Microsoft/vsts-zendesk-app#10]
We're seeing PBI fields that were selected in Zendesk to display disappear from the VSTS app. The fields display for a period of time but then stop displaying & we’re having to repeatedly add them back. Any idea why this might be happening?

**Comment by bfcamara** [comment]
The only thing that occurs to me that could be causing this is if you remove the app, and then upload it again. In that case the previous settings will be lost.

Are you you repro the problem in a consistent way?

**Comment by jenkrall** [comment]
We actually haven't removed the app for a while, so we're not thinking that would be the issue. It seems to break when we use the 'new work item' button in the app.

**Comment by bfcamara** [comment]
You mean the app looses its settings fields when you create the "new work item" button?

**Comment by jenkrall** [comment]
correct.

Jen Krall | Project Manager | CSM
Office: 262.701.9105
jkrall@skylinetechnologies.com<mailto:jkrall@skylinetechnologies.com>
N16 W23217 Stone Ridge Dr. Suite 200  Waukesha, WI 53188
<http://www.skylinetechnologies.com/>[1450730710484_Skyline]

________________________________

**Comment by bfcamara** [comment]
@jenkrall Weird. If you don't mind I'll send you an email to setup a skype call to figure out what's going on.

**Comment by jenkrall** [comment]
sounds good. thanks, Bruno!

Jen Krall | Project Manager | CSM
Office: 262.701.9105
jkrall@skylinetechnologies.com<mailto:jkrall@skylinetechnologies.com>
N16 W23217 Stone Ridge Dr. Suite 200  Waukesha, WI 53188
<http://www.skylinetechnologies.com/>[1450730710484_Skyline]

________________________________
