### ISSUE TITLE
Formatting of repro steps field

### ISSUE THREAD

**Issue by matt-sdg** [Microsoft/vsts-zendesk-app#11]
Hi,

The formatting of the zendesk comments (which ends up in VSTS repro steps) looses all line breaks when creating a bug. This makes bugs with a lot of information very hard to read. Not sure if this is a Zendesk issue and thus out of control for this app? Would appreciate if someone could look into this!

**Comment by bfcamara** [comment]
I managed to repro this issue. I'll take a look soon.

**Comment by jenkrall** [comment]
This same formatting issue is happening when creating a PBI. The comments end up in the description.

**Comment by bfcamara** [comment]
Fixed in new version 0.4.4
