### ISSUE TITLE
Fields displaying HTML in Zendesk 

### ISSUE THREAD

**Issue by jenkrall** [Microsoft/vsts-zendesk-app#12]
In Zendesk, certain fields are displaying HTML. I've seen this so far in the 'Acceptance Criteria' and 'Description' fields. Assigned to isn't displaying HTML but is displaying both the user name & e-mail. IMO - user name alone is sufficient.

![image](https://cloud.githubusercontent.com/assets/17648716/15294164/bfd07308-1b50-11e6-809a-75b93b3988f4.png)

**Comment by bfcamara** [comment]
Fixed in version 0.4.5

**Comment by jenkrall** [comment]
Awesome. Looks great – thank you, Bruno!!

Jen Krall | Project Manager | CSM, PMI-ACP
Office: 262.701.9105
jkrall@skylinetechnologies.com
N16 W23217 Stone Ridge Dr. Suite 200  Waukesha, WI 53188
[SkylineSignature]<http://www.skylinetechnologies.com/>
