### ISSUE TITLE
Tag not added to VSTS work item when linking to exiting work item

### ISSUE THREAD

**Issue by OliverMartini** [Microsoft/vsts-zendesk-app#18]
When linking a Zendesk ticket to an existing VSTS work item, the work item tag defined in the app configuration is not added to the existing work item.

**Comment by bfcamara** [comment]
Hi @OliverMartini 

This is intentional. The tag is only added for new work items, and it's the way to identify work items **created** from the app.

**Comment by OliverMartini** [comment]
Ok, thanks for clarification.
