### ISSUE TITLE
Add support for "Personal Access Tokens"

### ISSUE THREAD

**Issue by KasperLK** [Microsoft/vsts-zendesk-app#21]
Please add support for Personal access token.
According to this, alternate credentials is not recommended.
https://www.visualstudio.com/en-us/docs/git/auth-overview#alternate-credentials

**Comment by bfcamara** [comment]
In theory you could use a personal access token rather than an alternate credentials password. I tried a few months ago and I can remember that some API calls started to fail, even if the PAT was configured with all scopes/accounts.  Probably it is something that is already fixed.

**Comment by KasperLK** [comment]
It works, but there are some bugs.
Each item in the Project dropdown is shown 4 times.

**Comment by KasperLK** [comment]
Or not. Closing and reopening the browser fixed that.
