### ISSUE TITLE
Can't remove tag

### ISSUE THREAD

**Issue by KasperLK** [Microsoft/vsts-zendesk-app#22]
I can't delete the tag under App Configuration settings in Zendesk.
I can change it, but not leave it empty.

**Comment by bfcamara** [comment]
I managed to repro the problem. It seems an issue in Zendesk admin screen. The tag input is marked as "not required" with a default value of "zendesk". However, the zendesk admin screen, when changing the configuration of an installed app, if the field is set to empty value, the screen is setting the field with the default value.

The curious thing is that if you set the input as empty **while installing the app for the first time**, in that case the tag is set as empty, and no tag will be added in VSTS work items.

So, as workaround, you can uninstall the app, then install it again, and when prompted for configuration  for this first time, remove the tag value, and you should be OK.

**Comment by KasperLK** [comment]
Thanks
