### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by KasperLK** [Microsoft/vsts-zendesk-app#24]
I can't get comments to work.
Creating a VSTS work item from Zendesk works fine. My Zendesk service hook in VSTS is working, and I get an OK response back from Zendesk, but the comments don't show up in Zendesk.
It also don't work from Zendesk to VSTS.

**Comment by bfcamara** [comment]
Regarding VSTS->Zendesk, could you check in the service hook notification detail the tabs Request and Response? What do you see there? Could you also check what links (work item links) )the work item being commented has?

Regarding Zendesk->VSTS, are you using the notify button provided by the widget? If yes, has the ticket some tags starting with wi_?

**Comment by KasperLK** [comment]
All of my VSTS->Zendesk comments just showed up, but with about a 28 min delay.

I'm not using the notify button. The ticket has a vso_wi_365 tag, where 365 matches my work item number in VSTS

**Comment by KasperLK** [comment]
Ahh... I thought that all Internal note in Zendesk was sent to VSTS.
Using the Notify button works great, and the message shows up immediately.

Any advice on the delay from VSTS-> Zendesk?
If I look in the service hook history, the request is send immediately, so the delay must be in Zendesk.

**Comment by bfcamara** [comment]
I don't have any thought about the delay of VSTS->Zendesk. The first think I would check is the time of the VSTS notification to determine if the delay is on the VSTS side, or in Zendesk side. After that, based on what you find you probably need to ping the VSTS support, or the Zendesk support.

**Comment by KasperLK** [comment]
Thanks

**Comment by pmosupport** [comment]
Hi Guys

Could I please get some help on this..m

My vsts-> Zendesk comments are not being updated

Looked at the service hook I created and it's not firing as well

What am.i doing wrong?)

**Comment by ekozelek** [comment]
@KasperLK Did you find a fix for VSTS --> Zendesk comments? I am having trouble with this. 
![2019-03-05_1606](https://user-images.githubusercontent.com/38888740/53840806-ba81f480-3f60-11e9-9f67-dbf6b1d76774.png)
