### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by colinjp** [Microsoft/vsts-zendesk-app#32]
Using v 5.0 and ZD Pro, I do not seem to be able to access or find the password field of the Team Services app in Zendesk.

**Comment by willsmythe** [comment]
You can set your VSTS credentials (a [personal access token](https://docs.microsoft.com/en-us/vsts/accounts/use-personal-access-tokens-to-authenticate) is recommended) for the Zendesk app by clicking the person icon in the VSTS app's main view:

![image](https://user-images.githubusercontent.com/2503052/33736863-3abb3666-db62-11e7-931e-f85b0b5e1113.png)
