### ISSUE TITLE
VSTS widget does not recognize MS credentials for login

### ISSUE THREAD

**Issue by NewToZendesk** [Microsoft/vsts-zendesk-app#33]
open a request
want to create a VSTS work item
VSTS widget shows but it will not accept the current microsoft credentials.

Asks you to log in to VSTS rather than using your current credentials

Expected results:
Recognize my current MS credentials and put me through to VSTS.

**Comment by bfcamara** [comment]
You should use a Personal Access Token (PAT) for authentication as described here

https://www.visualstudio.com/en-us/docs/marketplace/integrate/service-hooks/services/zendesk

The widget doesn't support  Microsoft Account credentials. What you can use alternatively is your VSTS Alternate credentials but the recommended way is to use a PAT.

**Comment by willsmythe** [comment]
Using a PAT is recommended over alternate credentials since a PAT can be scoped to a specific account and specific functions.
