### ISSUE TITLE
Zendesk  App framwork v1 no longer accepted

### ISSUE THREAD

**Issue by KuleKnutta** [Microsoft/vsts-zendesk-app#35]
Get Upload Error:
Missing required key from translations/en.json: app.name

trying to install vsts-zendesk-app-0.5.0.zip

Would guess this is the problem: "Beginning August 1st, 2017, Zendesk will no longer permit uploads of new private apps using the v1 framework."
https://support.zendesk.com/hc/en-us/articles/115004453028-Announcing-Sunset-Apps-Framework-v1

Any plans for an update to v2?

**Comment by jakespirek** [comment]
Yikes, that's a big deal. Hopefully there is a plan for v2.

**Comment by thom-bringme** [comment]
https://developer.zendesk.com/apps/docs/apps-v2/migrating

**Comment by rvpomeren** [comment]
Is there a migrated version available yet?

**Comment by ScottGross** [comment]
Just tried adding this integration today and very disappointed to get stuck here. can anyone help here?

**Comment by bfcamara** [comment]
I've started to try to migrate this app by following the migration steps here

https://developer.zendesk.com/apps/docs/apps-v2/migrating

I thought that it would be easier.  I got stuck in the modal windows, since in V2 each modal instance is an iframe, hence not running in the same context of the side_bar. 

https://support.zendesk.com/hc/en-us/community/posts/115007388007-App-V1-modals-created-from-side-bar-how-to-migrate-

Now in V2, some communication is needed between side_bar and modals, which makes the migration more complex.

I think this app needs some rethinking to run in V2, rather than just direct migration.

**Comment by jakespirek** [comment]
If MS isn't going to do it, might be up to us to create one ourselves. Maybe someone can get a new Github repo started for people to contribute to.

**Comment by madkins1868** [comment]
Is migration required?   The sunset announcement from Zendesk says v1 apps should still work (only that new v1 apps wouldn't be allowed in the marketplace).  https://support.zendesk.com/hc/en-us/articles/115004453028-Announcing-Sunset-Apps-Framework-v1

**Comment by jakespirek** [comment]
You can update a v1 app that you've already installed but you can't install a v1 app that is new to your instance. So people who are just now trying to set up this integration are screwed.

**Comment by Eshen** [comment]
If folks are interested in potentially migrating this to v2, Zendesk has launched a v1->v2 migration tool available here:

https://github.com/zendesk/zendesk_app_migrator

For any issues, you can reach out to api@zendesk.com

**Comment by hromm** [comment]
Wow I hope someone will put this on V2

**Comment by rocchow** [comment]
we are just looking into the option of the integration.... unfortunately v1 is no longer be able to upload. really hope the v2 will come soon... many thanks for the contributors!

**Comment by cjames9001** [comment]
Is anyone from MS planning on updating this? I'd like to get this setup but if it is EOL and no longer going to be supported I don't want to invest the time to attempt to migrate this with the aforementioned tool.

**Comment by mapspiral** [comment]
I've currently migrated the tool myself but would appreciate an official release to support the v2 framework.

**Comment by vferris** [comment]
@mapspiral Can you share your migrated version?

**Comment by willsmythe** [comment]
We (Microsoft) are working on an official V2 compatiable app.

**Comment by spainb123** [comment]
Excellent @willsmythe , thanks for the update!

**Comment by ScottGross** [comment]
we are awaiting anxiously to get this integration back to our support team!

**Comment by cjames9001** [comment]
Great news! Thanks for the update!

**Comment by dbr2hb** [comment]
@willsmythe, do you have any update on when this fix is going to be available?

**Comment by royjanik** [comment]
Would also be interested in an update/timetable. I see that there's a v2 branch, but not sure what state it's in.

I was able to install the V1 app by bootstrapping it via a V2 shell, but I just got an email that V1 apps will cease to work entirely in March.

**Comment by sibbo73** [comment]
Is there any news on the support for V2 of the Zendesk application. This looks like an ideal integration but no use unless V2 support is provided. Any update on timescales?

**Comment by sibbo73** [comment]
Got a confirmation from @willsmythe that they hope to have something in November. Hopefully out should be available soon. Will be extremely useful in the support/development workflow. Don't know why zendesk don't fully integrate like they do with jira support.

**Comment by willsmythe** [comment]
V2 migration is completed. Grab the 0.6.0 release: https://github.com/Microsoft/vsts-zendesk-app/releases/tag/v0.6.0.
