### ISSUE TITLE
Can v0.6.2 be installed over an existing installation?

### ISSUE THREAD

**Issue by jasnichols1963** [Microsoft/vsts-zendesk-app#45]
I already have the integration with a previous version but now need to upgraded it to the V2 framework before March.

**Comment by miles-ash** [comment]
Be really helpful to know if this is possible as we have existing connections between Zendesk tickets and work items and I don't want those links to break if at all possible.

**Comment by NicolajHedeager** [comment]
You can use the update option on the existing app and upload the new zip file.
It will keep your existing ticket connections. I just did this on our own zendesk solution.

**Comment by jasnichols1963** [comment]
I just used the update option and it gives the appearance of working but then when I try to create a new work item, I get a very small dialog box and cannot enter any information. If I try to link to an existing work item, I get "Cannot read property 'queries' of undefined"

HELP!

**Comment by willsmythe** [comment]
This may have been an issue in 0.6.0. Grab the latest version (now 0.6.2) and see if this addresses your problem.
