### ISSUE TITLE
ZAF V2

### ISSUE THREAD

**Issue by swesharpth** [Microsoft/vsts-zendesk-app#46]
Hi,
Will the vsts-zendesk-app work under Zendesks new integration API ZAF V2? I got an email from Zendesk stating that the integration will be affected by the new API. More about the new API at https://developer.zendesk.com/apps/docs/developer-guide/migrating

Best regards,
Thomas

**Comment by willsmythe** [comment]
Version 0.6.0 is on ZAF V2
