### ISSUE TITLE
0.6.0 Issue - Updates 2 days ago - Now non-fonctionnal

### ISSUE THREAD

**Issue by maboulianne** [Microsoft/vsts-zendesk-app#47]
I dont know if its a Zendesk issue or the app itself

2 days ago we updated from 0.3.1 to 0.6.0 (related to the App V2 changes)

All was good, but now this morning, the logo is gone (just a small x)

And all button for (New Work Item, Link Work Item, Notify) are gone. Impossible to create new item to TFS).
![button gone](https://user-images.githubusercontent.com/28826841/35115587-badf98a4-fc56-11e7-965e-1fa15f258333.png)

![capture](https://user-images.githubusercontent.com/28826841/35115458-411b5814-fc56-11e7-8552-b245734c04f6.PNG)

**Comment by Lene2** [comment]
Seeing a similar issue today.  Upgraded 7 days ago with no issues - until now...
App is showing under Manage Apps but without the logo (as in the screen print in the original entry above) but is no longer shown in the Apps panel in the tickets...

**Comment by keval1986** [comment]
Our app is on Zendesk frame work V2.
Our VSTS App is now publicly available on Zendesk Marketplace. Since our App is public you can just install it from the MarketPlace of Zendesk. The team plan users can also install this app.
https://www.zendesk.com/apps/support/integratecloud-connector-for-vsts/

**Comment by willsmythe** [comment]
Fixed in 0.6.1
