### ISSUE TITLE
Needs for VSTS 

### ISSUE THREAD

**Issue by tperez311** [Microsoft/vsts-zendesk-app#50]
I am looking for information on how we’d integrate our Zendesk with our VSTS.

We need a flow that allows us to create a bug in VSTS from the Zendesk ticket – we’ll all of the current functionality of the Microsoft 0.6.0 version that exists today. 

We need a flow that would allow triggers that are set up in Zendesk to update information in VSTS.  For example, if a ticket in ZD is assigned a “Medium” or “Normal” priority and it’s linked to a VSTS bug item – could we create a trigger in ZD that escalates the priority from Medium or Normal after X amount of days/hours to a higher priority on the ZD ticket.  Once that trigger is ran in ZD, it would also automatically update the priority in VSTS to match.   Does this make sense?
We would also need the functionality of pushing information from VSTS back to ZD.  For example, if we have an open bug and the status is changed to RELEASED, or FIXED, or CLOSED – we’d want to push information back to the ZD ticket to mark the ticket as SOLVED.  This would need to work with existing ZD triggers that would also push out communication to the end-user that their issue was resolved.  In Zendesk, a PROBLEM type ticket can have child INCIDENT type tickets attached – we’d need the push from VSTS to make sure it closed all child tickets as well.  If you close a PROBLEM ticket in ZD, it automatically solves the child INCIDENT tickets.  Hopefully this all makes sense.  

I'm just curious to know if this functionality exists in this integration or if a third party application is needed.  

IntegrateCloud is a company that is selling their services promising this functionality - but if this functionality exists natively and there is documentation to support how to accomplish this functionality.. please point me in the right direction.

**Comment by keval1986** [comment]
Our app is on Zendesk frame work V2. 
Our vsts app is now publicly available on Zendesk Marketplace. Since our App is public you can just install it from the MarketPlace of Zendesk. The team plan users can also install this app.
https://www.zendesk.com/apps/support/integratecloud-connector-for-vsts/

**Comment by jasnichols1963** [comment]
Does it also support the functionality of VS-tagged notes coming back into the ticket as a private note?

**Comment by willsmythe** [comment]
@jasnichols1963 - this level of customization is probably best implemented using your solution. This will give you the level of control/flexibility you need. You *might* be able to use a service like [Microsoft Flow](https://flow.microsoft.com/en-us/connectors/shared_zendesk/zendesk/) or [Zapier](https://www.zendesk.com/apps/support/zapier/). [Azure Logic Apps](https://azure.microsoft.com/en-us/services/logic-apps/) is also an option.
