### ISSUE TITLE
Not Loading on First Use

### ISSUE THREAD

**Issue by robertlair** [Microsoft/vsts-zendesk-app#54]
I installed the app from the marketplace and went to an incident.  The app shows, but is stuck on "Loading" and never prompts for login information.  I have tried refreshing numerous times, but nothing.  
![image](https://user-images.githubusercontent.com/3609229/36751020-f84b50b2-1bcc-11e8-8d19-68dacf45f9ef.png)

**Comment by robertlair** [comment]
Additional Information, here is the error the app is receiving when stuck on loading: 

HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)POST - https://jjrsolutionssupport.zendesk.com/proxy/to/https%3A%2F%2Fintegratecloud.com%2FvstsApp%2FwebApi.aspx%2FGetVstsDomain

**Comment by Xep** [comment]
I think this is a different product developed by another company.

**Comment by robertlair** [comment]
I got to it via a link from this GitHub, https://github.com/Microsoft/vsts-zendesk-app/issues/40.  Was it perhaps another company trolling your GitHub to try to promote their own?

**Comment by Xep** [comment]
It is for sure different app.
This is not my rep., though :)

**Comment by willsmythe** [comment]
@robertlair - to close the loop on this ... the link (referenced in issue #40) is for another vendor's VSTS/Zendesk app. This app was not developed (or endorsed) by Microsoft. The comment was reported to GitHub and has been hidden. Sorry for the confusion.
