### ISSUE TITLE
Getting Error on Upload

### ISSUE THREAD

**Issue by 72Landry** [Microsoft/vsts-zendesk-app#55]
Upload Error
Could not find manifest.json in the root of the zip file, but dist/manifest.json was found. Try re-creating the archive from this directory.

Any insight?
Thanks!

**Comment by 72Landry** [comment]
Hello,

I was wondering is anyone could provide any insight to this error when uploading this APP to Zendesk???

Upload Error
Could not find manifest.json in the root of the zip file, but dist/manifest.json was found. Try re-creating the archive from this directory.

Is this App no good?

Thanks!
Jen

**Comment by sotiriszegiannis** [comment]
A new app for vsts has been launched. You can try it out from here:
https://www.zendesk.com/apps/support/integratecloud-connector-for-vsts/?source=app_directory

**Comment by willsmythe** [comment]
@72Landry  - the official (Microsoft-developed) VSTS app for Zendesk is only available as a download from this repo. See: https://github.com/Microsoft/vsts-zendesk-app/releases. Make sure you are downloading the release .zip (e.g. vsts-zendesk-app-0.6.1.zip) and not the source .zip.
