### ISSUE TITLE
VSTS Comments not working

### ISSUE THREAD

**Issue by pmosupport** [Microsoft/vsts-zendesk-app#66]
Hi All,

I can't get comments from VSTS to work.
Creating a VSTS work item from Zendesk works fine. 

My Zendesk service hook in VSTS is not working,. It created fine but it doesnt run and as such there is no update at all.

It  works from Zendesk to VSTS via the notify button only.

Please can i get some assistance.
![image](https://user-images.githubusercontent.com/41772123/43698429-3537e65a-998d-11e8-883b-3cc789545436.png)

**Comment by pmosupport** [comment]
closing this

**Comment by ekozelek** [comment]
@pmosupport Did you close this because you found a fix? If so, would you mind sharing it?
