### ISSUE TITLE
args is null when I try to create a workitem

### ISSUE THREAD

**Issue by andy6969** [Microsoft/vsts-zendesk-app#73]
Hi there,

First, I'd like to thank you for this excellent app we are already using with V1 framework.

Nevertheless, I have some difficulties to make the package for V2 work. I did the following : 

1. download and install the package from here https://github.com/Microsoft/vsts-zendesk-app/releases . Everything went fine and I could login my app with my vsts account.

2. When clicking on the button "create work item" I get an error that says "args is null". (see print screen)

What am I doing wrong ?
thank you for your help
Andreas

![screenshot_1024](https://user-images.githubusercontent.com/19251866/52718921-d703c000-2fa4-11e9-8903-52014d0d4d79.png)

**Comment by andy6969** [comment]
Hi Guys, I remove this issue, because I saw my error : I did not have the correct permissions in the VSTS.

**Comment by ekozelek** [comment]
I received this error too & wanted to note for others in the future that the Work Item Scope must be "Read/Write", not "Read/Write/Manage"
